#install:
#     - sudo apt-get install texlive-latex-recommended texlive-fonts-recommended
 
script:
    #- make
  - touch main.pdf

after_success:
  - echo "$DEPLOYKEY" > id_rsa
  - chmod 0600 id_rsa
  - GIT_SSH=./git_ssh.sh git clone git@github.com:ibab/demo-paper-output tmp
  - cp main.pdf tmp/main.pdf
  - cd tmp; git add main.pdf
  - git config --global user.name "Travis"
  - git config --global user.email "none"
  - cd tmp; git commit -m "Add PDF from travis"
  - cd tmp; GIT_SSH=./git_ssh.sh git push

