install:
  - sudo apt-get install texlive-latex-recommended texlive-fonts-recommended
 
script:
  - make

after_success:
  - echo "$DEPLOYKEY" > deploy.pem
  - chmod 600 deploy.pem
  - $(ssh-agent)
  - ssh-add deploy.pem
  - git clone git@github.com:ibab/demo-paper-output tmp
  - cp main.pdf tmp/main.pdf
  - cd tmp; git add main.pdf
  - cd tmp; git commit -m "Add PDF from travis"
  - cd tmp; git push

